name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main # or your deploy branch

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ§° Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: "stable"


      - name: ğŸ’¾ Restore pub cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: ğŸ“¦ Install dependencies
        working-directory: ./admin-panel
        run: flutter pub get

      - name: Create .env file
        working-directory: ./admin-panel
        run: |
          echo "FIREBASE_OPTIONS_API_KEY=${{ secrets.FIREBASE_OPTIONS_API_KEY }}" > .env
          echo "FIREBASE_OPTIONS_APP_ID=${{ secrets.FIREBASE_OPTIONS_APP_ID }}" >> .env
          echo "FIREBASE_OPTIONS_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_OPTIONS_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_OPTIONS_PROJECT_ID=${{ secrets.FIREBASE_OPTIONS_PROJECT_ID }}" >> .env
          echo "FIREBASE_OPTIONS_AUTH_DOMAIN=${{ secrets.FIREBASE_OPTIONS_AUTH_DOMAIN }}" >> .env
          echo "FIREBASE_OPTIONS_STORAGE_BUCKET=${{ secrets.FIREBASE_OPTIONS_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_OPTIONS_MEASUREMENT_ID=${{ secrets.FIREBASE_OPTIONS_MEASUREMENT_ID }}" >> .env
          echo "MAILGUN_DOMAIN=${{ secrets.MAILGUN_DOMAIN }}" >> .env
          echo "MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }}" >> .env

      - name: ğŸ› ï¸ Generate Envied files
        working-directory: ./admin-panel
        run: dart run build_runner build -d

      - name: ğŸŒ Build Flutter Web
        working-directory: ./admin-panel
        run: flutter build web --release

      - name: ğŸ”¥ Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live # or preview for preview channels
          projectId: simdte-conference
          target: default
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
